# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgZz40EqqbsW2TD3tFafsCsIPRtZmJCE
"""



"""Hand written digit prediction -classification analysis

the digit dataset consist of 8x8 pixel images of digit. the images attributes of the dataset atores 8x8 arrayes of grayscale value for each images.we will use these arrays to visualize the first 4 images. the taarget atttribute of the dataset stores the digit rach images represent

Import Library
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as pit

"""Import Data"""

from sklearn.datasets import load_digits

df = load_digits()

_, axes = pit.subplots(nrows=1, ncols=4, figsize=(10, 3))
for ax, image, label in zip(axes, df.images, df.target):
    ax.set_axis_off()
    ax.imshow(image, cmap=pit.cm.gray_r, interpolation="nearest")
    ax.set_title("Training: %i" % label)

"""Data  preprocessing

flatten image

:
"""

df.images.shape

df.images[0]

df.images[0].shape

len(df.images)

n_samples = len(df.images)
data = df.images.reshape((n_samples, -1))

data[0]

data[0].shape

data.shape

"""Scaling image Data"""

data.min()

data.max()

data = data/16

data.min()

data[0]

"""Train test split data"""

from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test = train_test_split(data, df.target, test_size=0.25, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""Random forest Model"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

"""Predict test data"""

y_pred = rf.predict(X_test)

y_pred

"""Model Accuracy"""

from sklearn. metrics import confusion_matrix, classification_report

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))